### ISSUE TITLE
Feature request: run against existing plex library

### ISSUE THREAD

**Issue by xenoguy** [mjvotaw/plex-sub-downloader#11]
is there a way to run this against an existing plex library?  like the "check-video" command but for a whole library.

thanks for the project, appreciate it!

**Comment by ghost** [comment]
Currently there's no way to run this against an entire library. The main issue here is that a lot of subtitle providers have rate limits, which means that we can't just load up all of the media and check them all in one go. I'm trying to work on a newer version of this application that will eventually provide this sort of features, but it won't be ready any time soon.

**Comment by mjvotaw** [comment]
I just released a new feature that will automatically try to download and enable the subtitles for the next episode of whatever tv shows you and your users are watching (assuming that you've got subtitles enabled on the current episode, of course). I don't know if that will help your situation out or not, but just wanted to let you know.

**Comment by xenoguy** [comment]
I wrote my own script queries the plex sqlite db to find all items and loops through them using this sub downloader.  so problem solved for me.
