### ISSUE TITLE
ValueError when converting parentTitle (Specials) to int.

### ISSUE THREAD

**Issue by jeff08568** [mjvotaw/plex-sub-downloader#6]
plex-sub-downloader does not seem to handle non-number seasons like "Specials" in Plex. The issue occur when trying to convert the parentTitle attribute of a video object to an integer in order to extract the season number, which is not an integer is this case?

**Steps to Reproduce:**
plex_sub_downloader --config config.json check-video /library/metadata/"<any metadata item with specials>"

**Expected Behaviour**
Handleds parentTitle without raising ValueError

**Additional Information:**
I'm running the script in a Python 3.10 environment.
I've noticed that the error occurs specifically when the parentTitle contains the string "Specials." Other season numbers (e.g., "Season 1," "Season 2") seem to be handled correctly.

**Comment by ghost** [comment]
Yeah, that's not something I'd even considered. I'll have to look into this.

**Comment by ghost** [comment]
Okay, so turns out I'm just not very good at reading documentation, and Python PlexAPI explicitly provides the season and episode numbers. I've just pushed up a new version that should fix this issue.
