### ISSUE TITLE
Typo in readme.md

### ISSUE THREAD

**Issue by nequam** [mjvotaw/plex-sub-downloader#8]
Kinda funny and so not severe. The sample config file, at the VERY END of the page, mentions a language, "es," and the code first complained that "es" wasn't a language.

Change: 

```
"languages": [ 
  "eng", 
  "es" 
],
```

to

```
"languages": [
   "eng"
 ],

```

**Comment by ghost** [comment]
Ah jeez. Thanks, I'll get that fixed.
