### ISSUE TITLE
Does this work when plex is on docker?

### ISSUE THREAD

**Issue by zDuts** [mjvotaw/plex-sub-downloader#9]
Whatever i do i can't get the debug logging to show anything when i play a video. The webhooks get added and i tried 10 different hosts and port combos but it never shows anything in the logging. 
Does this work with Plex running on docker?
How do i know which host to use?
I'm on ubuntu 22.04 oracle free tier vps.

**Comment by ghost** [comment]
Hey sorry for not getting to this sooner. You should be able to use this with Docker just fine. One thing that you do need to do is make sure [push notifications](https://support.plex.tv/articles/push-notifications/) are enabled on your Plex server. For some reason this has to be enabled before webhooks will work.

And as for your host/port, it should just be whatever you'd use to get to your local Plex server (ie 'http://device-name:32400' or 'http://ip-address:32400', or 'http://localhost:32400' if you're running it from the same machine).
